In [5]:
import cv2
import pickle
import numpy as np
import os
video=cv2.VideoCapture(0)
facedetect=cv2.CascadeClassifier('data/haarcascade_frontalface_default.xml')

faces_data=[]

i=0


while True:
    ret,frame=video.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces=facedetect.detectMultiScale(gray, 1.3 ,5)
    for (x,y,w,h) in faces:
        crop_img=frame[y:y+h, x:x+w, :]
        resized_img=cv2.resize(crop_img, (50,50))
        print(resized_img)
        if len(faces_data)<=100 and i%10==0:
            faces_data.append(resized_img)
        i=i+1
        cv2.putText(frame, str(i), (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (50,50,255), 1)
        cv2.rectangle(frame, (x,y), (x+w, y+h), (50,50,255), 1)
    cv2.imshow("Frame",frame)
    k=cv2.waitKey(1)
    if k==ord('q') or i==1:
        break
video.release()
cv2.destroyAllWindows()
faces_data=np.asarray(faces_data).flatten() 
print(faces_data)

[[[ 56  52  52]
  [ 66  54  53]
  [ 44  35  36]
  ...
  [ 91 101 106]
  [ 52  65  83]
  [ 43  57  87]]

 [[ 54  49  51]
  [ 53  47  49]
  [ 35  28  32]
  ...
  [106 114 124]
  [ 58  66  84]
  [ 48  59  84]]

 [[ 48  41  44]
  [ 41  38  38]
  [ 34  30  30]
  ...
  [117 125 129]
  [ 53  66  79]
  [ 48  62  85]]

 ...

 [[118 120 149]
  [110 118 149]
  [103 116 145]
  ...
  [152 148 158]
  [ 60  67  86]
  [ 41  61  90]]

 [[109 118 148]
  [106 118 152]
  [103 121 152]
  ...
  [152 149 156]
  [ 60  66  85]
  [ 42  60  94]]

 [[112 122 155]
  [104 126 154]
  [ 99 124 152]
  ...
  [153 150 158]
  [ 58  64  84]
  [ 41  56  90]]]
[56 52 52 ... 41 56 90]


In [ ]:
pip install face_recognition


In [ ]:
pip install cmake


In [ ]:
pip install dlib


In [ ]:
import pickle
with open('data/Emails.pkl', 'rb') as f:
            EMAILS = pickle.load(f)
            print(EMAILS)

In [ ]:
with open('data/faces_data.pkl', 'rb') as f:
    FACES=pickle.load(f)
    print(FACES[:5])


In [ ]:
with open('data/names.pkl', 'rb') as w:
    LABELS=pickle.load(w)
    print(LABELS)

In [ ]:
import cv2
import pickle
import numpy as np
import os
video=cv2.VideoCapture(0)
facedetect=cv2.CascadeClassifier('data/haarcascade_frontalface_default.xml')

faces_data=[]

i=0

name=input("Enter Your Name: ")

while True:
    ret,frame=video.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces=facedetect.detectMultiScale(gray, 1.3 ,5)
    for (x,y,w,h) in faces:
        print(x,y,w,h)
        crop_img=frame[y:y+h, x:x+w, :]
        resized_img=cv2.resize(crop_img, (50,50))
        if len(faces_data)<=100 and i%10==0:
            faces_data.append(resized_img)
            print(faces_data)
        i=i+1
        cv2.putText(frame, str(len(faces_data)), (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (50,50,255), 1)
        cv2.rectangle(frame, (x,y), (x+w, y+h), (50,50,255), 1)
    cv2.imshow("Frame",frame)
    k=cv2.waitKey(1)
    if k==ord('q') or len(faces_data)==4:
        break
video.release()
cv2.destroyAllWindows()
