In [3]:
import cv2
import pickle
import numpy as np
import os
video=cv2.VideoCapture(0)
facedetect=cv2.CascadeClassifier('data/haarcascade_frontalface_default.xml')

faces_data=[]

i=0

name=input("Enter Your Name: ")

while True:
    ret,frame=video.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces=facedetect.detectMultiScale(gray, 1.3 ,5)
    for (x,y,w,h) in faces:
        crop_img=frame[y:y+h, x:x+w, :]
        resized_img=cv2.resize(crop_img, (50,50))
        print(resized_img)
        i=i+1
        cv2.putText(frame, str(i), (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (50,50,255), 1)
        cv2.rectangle(frame, (x,y), (x+w, y+h), (50,50,255), 1)
    cv2.imshow("Frame",frame)
    k=cv2.waitKey(1)
    if k==ord('q') or i==10:
        break
video.release()
cv2.destroyAllWindows()

Enter Your Name:  piyush


[[[ 25  24  28]
  [ 27  22  28]
  [ 29  23  27]
  ...
  [160 157 162]
  [120 122 126]
  [175 175 189]]

 [[ 22  24  26]
  [ 26  22  27]
  [ 28  24  28]
  ...
  [ 91  81  87]
  [130 128 135]
  [148 151 163]]

 [[ 23  22  26]
  [ 28  22  29]
  [ 28  22  30]
  ...
  [ 90  80  91]
  [126 118 138]
  [161 163 187]]

 ...

 [[ 71  68 122]
  [ 50  45 130]
  [ 56  53 139]
  ...
  [ 27  42  64]
  [ 30  45  68]
  [ 31  45  67]]

 [[ 57  65 111]
  [ 47  46 121]
  [ 54  51 140]
  ...
  [ 25  40  62]
  [ 28  39  62]
  [ 32  43  65]]

 [[ 51  56 109]
  [ 56  49 122]
  [ 61  49 138]
  ...
  [ 24  37  59]
  [ 24  37  59]
  [ 32  44  66]]]
[[[ 23  22  24]
  [ 22  20  25]
  [ 25  24  28]
  ...
  [171 169 171]
  [127 126 130]
  [154 152 165]]

 [[ 21  19  24]
  [ 23  21  26]
  [ 25  21  26]
  ...
  [105 100 104]
  [129 130 135]
  [164 166 176]]

 [[ 26  20  25]
  [ 20  17  25]
  [ 24  20  26]
  ...
  [ 79  67  78]
  [104  95 109]
  [147 145 159]]

 ...

 [[ 59  64 116]
  [ 50  49 118]
  [ 49  46 128]
  ..

In [1]:
pip install face_recognition


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install cmake


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install dlib


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [12]:
import pickle
with open('data/Emails.pkl', 'rb') as f:
            EMAILS = pickle.load(f)
            print(EMAILS)

FileNotFoundError: [Errno 2] No such file or directory: 'data/Emails.pkl'

In [4]:
with open('data/faces_data.pkl', 'rb') as f:
    FACES=pickle.load(f)
    print(FACES[:5])


[[21 22 15 ... 45 54 53]
 [32 27 24 ... 35 42 42]
 [31 30 24 ... 26 39 39]
 [27 26 23 ... 40 50 52]
 [41 36 39 ... 22 29 30]]


In [9]:
with open('data/names.pkl', 'rb') as w:
    LABELS=pickle.load(w)
    print(LABELS)

['Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush']

In [7]:
import cv2
import pickle
import numpy as np
import os
video=cv2.VideoCapture(0)
facedetect=cv2.CascadeClassifier('data/haarcascade_frontalface_default.xml')

faces_data=[]

i=0

name=input("Enter Your Name: ")

while True:
    ret,frame=video.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces=facedetect.detectMultiScale(gray, 1.3 ,5)
    for (x,y,w,h) in faces:
        print(x,y,w,h)
        crop_img=frame[y:y+h, x:x+w, :]
        resized_img=cv2.resize(crop_img, (50,50))
        if len(faces_data)<=100 and i%10==0:
            faces_data.append(resized_img)
            print(faces_data)
        i=i+1
        cv2.putText(frame, str(len(faces_data)), (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (50,50,255), 1)
        cv2.rectangle(frame, (x,y), (x+w, y+h), (50,50,255), 1)
    cv2.imshow("Frame",frame)
    k=cv2.waitKey(1)
    if k==ord('q') or len(faces_data)==4:
        break
video.release()
cv2.destroyAllWindows()


Enter Your Name:  piyush


262 49 47 47
[array([[[176, 182, 191],
        [178, 183, 192],
        [180, 185, 194],
        ...,
        [253, 254, 254],
        [254, 255, 252],
        [255, 255, 250]],

       [[177, 182, 191],
        [178, 183, 192],
        [180, 185, 195],
        ...,
        [252, 254, 254],
        [254, 255, 252],
        [255, 255, 250]],

       [[176, 181, 191],
        [177, 182, 192],
        [180, 184, 195],
        ...,
        [252, 254, 254],
        [253, 255, 251],
        [255, 255, 250]],

       ...,

       [[159, 165, 180],
        [159, 165, 181],
        [160, 167, 182],
        ...,
        [216, 219, 231],
        [196, 199, 216],
        [200, 203, 223]],

       [[162, 166, 181],
        [161, 166, 182],
        [161, 167, 182],
        ...,
        [220, 219, 233],
        [199, 199, 218],
        [199, 200, 223]],

       [[163, 167, 181],
        [162, 167, 182],
        [161, 168, 182],
        ...,
        [225, 221, 237],
        [207, 206, 225],
        [2