In [10]:
from sklearn.neighbors import KNeighborsClassifier
import cv2
import pickle
import numpy as np
import os
import csv
import time
from datetime import datetime
from win32com.client import Dispatch

def speak(str1):
    speak = Dispatch(("SAPI.SpVoice"))
    speak.Speak(str1)

video = cv2.VideoCapture(0)
facedetect = cv2.CascadeClassifier('data/haarcascade_frontalface_default.xml')

with open('data/names.pkl', 'rb') as w:
    LABELS = pickle.load(w)
with open('data/faces_data.pkl', 'rb') as f:
    FACES = pickle.load(f)

print('Shape of Faces matrix --> ', FACES.shape)
FACES = FACES / 255.0  # Normalize training faces
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(FACES, LABELS)

imgBackground = cv2.imread("background.png")

COL_NAMES = ['NAME', 'TIME']

while True:
    ret, frame = video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = facedetect.detectMultiScale(gray, 1.3, 5)

    for (x, y, w, h) in faces:
        crop_img = frame[y:y+h, x:x+w, :]
        resized_img = cv2.resize(crop_img, (50, 50)).flatten().reshape(1, -1) / 255.0  # Normalize test face

        distances, indices = knn.kneighbors(resized_img)
        
        threshold = 9  # Adjust based on your data
        
        if distances[0][0] > threshold:
            output = ["Unknown"]
        else:
            output = knn.predict(resized_img)
        
       # print("Distances:", distances, "Output:", output)

        ts = time.time()
        date = datetime.fromtimestamp(ts).strftime("%d-%m-%Y")
        timestamp = datetime.fromtimestamp(ts).strftime("%H:%M:%S")
        exist = os.path.isfile("Attendance/Attendance_" + date + ".csv")

        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 0, 255), 1)
        cv2.rectangle(frame, (x, y), (x+w, y+h), (50, 50, 255), 2)
        cv2.rectangle(frame, (x, y-40), (x+w, y), (50, 50, 255), -1)
        cv2.putText(frame, str(output[0]), (x, y-15), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 1)
        attendance = [str(output[0]), str(timestamp)]

    imgBackground[162:162 + 480, 55:55 + 640] = frame
    cv2.imshow("Frame", imgBackground)
    k = cv2.waitKey(1)

    if k == ord('o') and output[0] != "Unknown":
        speak("Attendance Taken..")
        time.sleep(3)
        if exist:
            with open("Attendance/Attendance_" + date + ".csv", "+a") as csvfile:
                writer = csv.writer(csvfile)
                writer.writerow(attendance)
        else:
            with open("Attendance/Attendance_" + date + ".csv", "+a") as csvfile:
                writer = csv.writer(csvfile)
                writer.writerow(COL_NAMES)
                writer.writerow(attendance)

    if k == ord('q'):
        break

video.release()
cv2.destroyAllWindows()


Shape of Faces matrix -->  (200, 7500)


In [1]:
import pickle
with open('data/names.pkl', 'rb') as w:
    LABELS=pickle.load(w)
    print(LABELS)

['Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush']

In [3]:
import pickle
with open('data/faces_data.pkl', 'rb') as f:
    FACES=pickle.load(f)
    print(FACES)

[[ 36  30  29 ...  38  34  35]
 [ 31  29  33 ...  39  27  36]
 [ 29  25  28 ...  40  34  40]
 ...
 [ 21 148 197 ...  38  88 125]
 [ 20 148 197 ...   2   3  35]
 [ 18 147 194 ...  44 127 174]]


In [2]:
import pickle
with open('data/Emails.pkl', 'rb') as f:
    EMAILS = pickle.load(f)
    print(EMAILS)

['infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gmail.com', 'infopiyush2004@gma

In [1]:
import tkinter as tk

root = tk.Tk()
root.configure(bg="#f0f0f0")

label_name = tk.Label(root, text="Enter Your Name:", font=("Arial", 15), bg="#f0f0f0")
label_name.pack(pady=5)
entry_name = tk.Entry(root, width=35)
entry_name.pack(pady=8)

label_email = tk.Label(root, text="Enter Your Email:", font=("Arial", 15), bg="#f0f0f0")
label_email.pack(pady=5)
entry_email = tk.Entry(root, width=35)
entry_email.pack(pady=8)

def reset_form():
    label_name.config(text="Enter Your Name:")   
    label_email.config(text="Enter Your Email:") 
    entry_name.delete(0, tk.END)                
    entry_email.delete(0, tk.END)               

tk.Button(root, text="Reset", command=reset_form).pack(pady=10)

root.mainloop()
